### ISSUE TITLE
Permissions Bug with creating Alarms in Cloudwatch

### ISSUE THREAD

**Issue by TyReed12** [ActoKids/web-crawler#15]
I'm get a permissions denied notification when I try and create a notification list in alarms in CloudWatch.

**Comment by TyReed12** [comment]
![alarmerror](https://user-images.githubusercontent.com/34496119/53653877-3c8cb900-3c01-11e9-8f8a-58dbed445bc1.JPG)

**Comment by jams2018** [comment]
@TyReed12 The policy has been modified. Would you try it one more time and let me know?

**Comment by jams2018** [comment]
![cloudwatch_simulation](https://user-images.githubusercontent.com/38123178/53679332-3689ed00-3c80-11e9-81ac-27c7f4972893.PNG)

**Comment by TyReed12** [comment]
@jams2018  @LyndonP  @amy61789  I still cannot create a notification list which is the action the alarm does when alarm is triggered.

This is the documentation I'm using to create the alarm: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ConsoleAlarms.html

**Comment by TyReed12** [comment]
![alarmerror](https://user-images.githubusercontent.com/34496119/53701646-18bda480-3db4-11e9-92eb-9dfab743f601.JPG)

**Comment by dashinay** [comment]
I have created a test user and assigned all permission from your user account, then recreated your steps. I found the issue related to the permission.

**Cause of the issue:** Whenever you tried to create a notification list you actually have been trying to create a SNS topic. You have been given permissions for CloudWatch but because SNS is a separate service you didn't had an access. 

**Solution**: I have added SNS permissions to your account.

I have tested it on a test user and it worked, could you check it and let me know.

**Comment by TyReed12** [comment]
Fixed! Thanks Dawit. I will close the issue.
